services:
  - type: web
    name: laravel-app
    runtime: docker
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
    buildCommand: |
      rm -rf vendor composer.lock
      curl -sS https://getcomposer.org/installer | php
      mv composer.phar /usr/local/bin/composer
      composer install --no-dev --optimize-autoloader
      php artisan config:clear
      php artisan cache:clear
      php artisan view:clear
      php artisan route:clear
      php artisan migrate --force
    startCommand: |
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan serve --host 0.0.0.0 --port 10000
