services:
  - type: web
    name: laravel-app
    runtime: docker
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:clear
      php artisan cache:clear
      php artisan view:clear
      php artisan route:clear
      php artisan migrate --force
    startCommand: |
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
